package logo.lexer;

// Compiled

public enum TokenType {
	LEFT_BRACE, RIGHT_BRACE, COMMA, MINUS, PLUS, SLASH, STAR, DOT, COLON,

	BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

	IDENTIFIER,

	STRING, NUMBER,

	TRUE, FALSE,

	IF, TEST, IFELSE, IFTRUE, IFFALSE, STOP,
	FOR, UNTIL, DOUNTIL, WHILE, DOWHILE, REPEAT,
	RUN, 
	FOREVER, REPCOUNT,
	MOUSEPOS, CLICKPOS, BACKGROUND, BG, GETSCREENCOLOR, GETSC,
	FORWARD, BACK, RIGHT, LEFT,
	CS, CLEARSCREEN, PU, PENUP, PD, PENDOWN, TO, END, PENMODE, PAINT, ERASE, REVERSE, SETPENCOLOR,
	SETPENSIZE, SETBACKGROUND, SETSCREENCOLOR, SETSC,
	SETPOS, SETXY, SETX, SETY, AND, OR, NOT, XOR,
	SHOW, MAKE, LOCAL,

	RANDOM,

	NULL,

	EOF
};
